"""Initial migration

Revision ID: d80f98388046
Revises:
Create Date: 2025-12-30 13:34:30.842044

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd80f98388046'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('transport', sa.Enum('SSE', 'HTTP', 'STDIO', name='mcpservertransport'), nullable=False),
        sa.Column('url', sa.String(255), nullable=True),
        sa.Column('command', sa.String(255), nullable=True),
        sa.Column('arguments', sa.JSON(), nullable=True),
        sa.Column('port', sa.Integer(), nullable=True),
        sa.Column('envs', sa.JSON(), nullable=True),
        sa.Column('headers', sa.JSON(), nullable=True),
        sa.Column('tools', sa.JSON(), nullable=True),
        sa.Column('task_install', sa.String(255), nullable=True),
        sa.Column('task_uninstall', sa.String(255), nullable=True),
        sa.Column('autostart', sa.Boolean(), nullable=False),
        sa.Column('autorestart', sa.String(255), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('startsecs', sa.Integer(), nullable=False),
        sa.Column('startretries', sa.Integer(), nullable=False),
        sa.Column('stopsignal', sa.String(255), nullable=False),
        sa.Column('stopwaitsecs', sa.Integer(), nullable=False),
        sa.Column('log_level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
        sa.Column('stdout_logfile', sa.String(255), nullable=True),
        sa.Column('stdout_logfile_maxbytes', sa.Integer(), nullable=False),
        sa.Column('stdout_logfile_backups', sa.Integer(), nullable=False),
        sa.Column('redirect_stderr', sa.Boolean(), nullable=False),
        sa.Column('stderr_logfile', sa.String(255), nullable=True),
        sa.Column('stderr_logfile_maxbytes', sa.Integer(), nullable=False),
        sa.Column('stderr_logfile_backups', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('synced_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='synctaskstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=False),
        sa.Column('current_step', sa.String(255), nullable=False),
        sa.Column('log_file_path', sa.String(255), nullable=True),
        sa.Column('error_message', sa.String(255), nullable=True),
        sa.Column('servers_processed', sa.Integer(), nullable=False),
        sa.Column('total_servers', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_tasks')
    op.drop_table('servers')
    # ### end Alembic commands ###
