"""consolidated_initial_migration

Revision ID: f2665251d756
Revises:
Create Date: 2026-01-01 10:12:42.564243

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f2665251d756'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('transport', sa.String(length=5), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('command', sa.String(), nullable=True),
        sa.Column('arguments', sa.JSON(), nullable=False),
        sa.Column('port', sa.Integer(), nullable=True),
        sa.Column('envs', sa.JSON(), nullable=False),
        sa.Column('headers', sa.JSON(), nullable=False),
        sa.Column('tools', sa.JSON(), nullable=False),
        sa.Column('task_install', sa.String(), nullable=True),
        sa.Column('task_uninstall', sa.String(), nullable=True),
        sa.Column('autostart', sa.Boolean(), nullable=False),
        sa.Column('autorestart', sa.String(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('startsecs', sa.Integer(), nullable=False),
        sa.Column('startretries', sa.Integer(), nullable=False),
        sa.Column('stopsignal', sa.String(), nullable=False),
        sa.Column('stopwaitsecs', sa.Integer(), nullable=False),
        sa.Column('log_level', sa.String(length=8), nullable=False),
        sa.Column('stdout_logfile', sa.String(), nullable=True),
        sa.Column('stdout_logfile_maxbytes', sa.Integer(), nullable=False),
        sa.Column('stdout_logfile_backups', sa.Integer(), nullable=False),
        sa.Column('redirect_stderr', sa.Boolean(), nullable=False),
        sa.Column('stderr_logfile', sa.String(), nullable=True),
        sa.Column('stderr_logfile_maxbytes', sa.Integer(), nullable=False),
        sa.Column('stderr_logfile_backups', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('synced_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status', sa.String(length=9), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=False),
        sa.Column('current_step', sa.String(), nullable=False),
        sa.Column('log_file_path', sa.String(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('servers_processed', sa.Integer(), nullable=False),
        sa.Column('total_servers', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_snapshots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('cpu_percent', sa.Float(), nullable=False),
        sa.Column('memory_percent', sa.Float(), nullable=False),
        sa.Column('load_average', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_snapshot_processes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('snapshot_id', sa.Integer(), nullable=False),
        sa.Column('pid', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('state', sa.String(), nullable=False),
        sa.Column('ppid', sa.Integer(), nullable=True),
        sa.Column('uptime', sa.Integer(), nullable=True),
        sa.Column('memory_rss', sa.Integer(), nullable=True),
        sa.Column('memory_percent', sa.Float(), nullable=True),
        sa.Column('cpu_percent', sa.Float(), nullable=True),
        sa.Column('user', sa.String(), nullable=True),
        sa.Column('command', sa.String(), nullable=True),
        sa.Column('arguments', sa.String(), nullable=True),
        sa.Column('cwd', sa.String(), nullable=True),
        sa.Column('manager', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('exit_code', sa.Integer(), nullable=True),
        sa.Column('num_threads', sa.Integer(), nullable=True),
        sa.Column('nice', sa.Integer(), nullable=True),
        sa.Column('io_read_bytes', sa.Integer(), nullable=True),
        sa.Column('io_write_bytes', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['snapshot_id'], ['system_snapshots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_snapshot_processes')
    op.drop_table('system_snapshots')
    op.drop_table('sync_tasks')
    op.drop_table('servers')
    # ### end Alembic commands ###
