from __future__ import annotations

from pathlib import Path
from textwrap import dedent
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field


if TYPE_CHECKING:
    from src.backend.models import ServerConfiguration


class FastMcpServerProxyServerFile(BaseModel):
    """FastMCP server that acts as a proxy to MCP server defined in mcpServers.json."""

    server_name: str = Field(description="Name of the MCP server")
    json_file_path: str = Field(description="Path to mcpServers.json configuration file")

    @classmethod
    def from_mcp_server_config(cls, config: ServerConfiguration, json_file_path: str) -> "FastMcpServerProxyServerFile":
        """Create FastMcpServerProxyServerFile from MCPServerConfig, extracting relevant fields."""
        return cls(
            server_name=config.name,
            json_file_path=json_file_path
        )

    def __str__(self) -> str:
        config_path = Path(self.json_file_path).resolve().as_posix()
        return dedent(f"""
            \"\"\"MCP Server Proxy - Generated by mcpzoo\"\"\"
            from fastmcp import FastMCP
            import json
            from pathlib import Path
            
            # Load MCP server configuration from mcpServers.json
            config_file = Path("{config_path}")
            config = json.loads(config_file.read_text())
            
            # Create proxy server from config 
            mcp = FastMCP.as_proxy(config, name="{self.server_name}")
            
            # Note:
            # Server name must be `mcp` to allow `fastmcp run server.py` to recognize it.
        """).strip()
