import json

from datetime import datetime
from pathlib import Path
from typing import List

from fastapi import APIRouter, Depends, HTTPException, status

from src.backend.auth import verify_token
from src.backend.models import Server, ServerCreateOrUpdateRequest, timezone
from src.backend.services.database import DatabaseService, get_database_service
from src.backend.services.logging import logger
from src.backend.services.port_manager import PortManagerService, get_port_manager_service
from src.backend.services.supervisor import SupervisorService, get_supervisor_service
from src.backend.settings import get_settings


settings = get_settings()
router = APIRouter(prefix="/api/servers", tags=["servers"])


@router.get("", response_model=List[Server])
async def list_servers(
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
):
    """List all MCP servers."""
    logger.info(f"list_servers called by user: {username}")
    try:
        db = db_service.get_db()
        servers = db.get_all_servers()
        logger.info(f"Found {len(servers)} servers")
        return servers
    except Exception as e:
        logger.error(f"Error in list_servers: {str(e)}")
        raise


@router.get("/{server_id}", response_model=Server)
async def get_server(
    server_id: int,
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
):
    """Get specific server."""
    logger.info(f"get_server called by user: {username} for server_id: {server_id}")
    try:
        db = db_service.get_db()
        server = db.get_server(server_id)

        if not server:
            logger.warning(f"Server not found: {server_id}")
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Server not found",
            )

        logger.info(f"Successfully retrieved server: {server_id}")
        return server
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in get_server for {server_id}: {str(e)}")
        raise


@router.post("", status_code=status.HTTP_201_CREATED, response_model=Server)
async def create_server(
    server_data: ServerCreateOrUpdateRequest,
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
    port_manager: PortManagerService = Depends(get_port_manager_service),
):
    """Create a new MCP server."""
    # Assign port (id will be auto-generated by database)
    port = port_manager.get_next_mcp_server_available_port()

    # Convert request to Server Pydantic model
    server_dict = server_data.model_dump()
    server_dict["port"] = port
    server_dict["created_at"] = datetime.now(timezone.utc)

    server = Server.model_validate(server_dict)

    # Persist to database
    db = db_service.get_db()
    server_record = server.to_sa_record()
    created_server = db.insert_server(server_record)

    return created_server



@router.put("/{server_id}", response_model=Server)
async def update_server(
    server_id: int,
    server_data: ServerCreateOrUpdateRequest,
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
    port_manager: PortManagerService = Depends(get_port_manager_service),
):
    """Update server configuration."""
    db = db_service.get_db()
    existing_server = db.get_server(server_id)
    if not existing_server:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Server not found",
        )

    # Update with new data (keep id, created_at)
    updated_data = server_data.model_dump()
    updated_data["id"] = server_id
    updated_data["created_at"] = existing_server.created_at
    updated_data["updated_at"] = datetime.now(timezone.utc)
    updated_data["synced_at"] = existing_server.synced_at

    # Assign port
    updated_data["port"] = port_manager.get_next_mcp_server_available_port()

    # Validate and persist
    updated_server = Server.model_validate(updated_data)
    server_record = updated_server.to_sa_record()
    result = db.update_server(server_id, server_record)

    return result


@router.get("/{server_id}/logs")
async def get_server_logs(
    server_id: int,
    type: str = "stdout",
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
):
    """Get logs for a specific server.

    Type can be 'stdout' or 'stderr'.
    Returns last 100 lines of the requested logfile.
    """
    db = db_service.get_db()
    server = db.get_server(server_id)
    if not server:
        raise HTTPException(status_code=404, detail="Server not found")
    
    log_file = f"/var/log/supervisor/mcp_{server['name']}_{type}.log"
    
    try:
        with open(log_file, 'r') as f:
            lines = f.readlines()
            content = ''.join(lines[-100:])
        
        return {
            "server_name": server['name'],
            "type": type,
            "content": content,
        }
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail=f"Log file not found for {type}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error reading logs: {str(e)}")

@router.delete("/{server_id}", status_code=204)
async def delete_server(
    server_id: int,
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
):
    """Delete server configuration."""
    db = db_service.get_db()
    server = db.get_server(server_id)
    if not server:
        raise HTTPException(
            status_code=404,
            detail="Server not found",
        )
    db.delete_server(server_id)
    return None

@router.get("/mcp-config", response_model=dict)
async def get_mcp_config(
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
):
    """Generate mcpServer.json configuration for FastMCP proxy server."""
    db = db_service.get_db()
    servers = db.get_all_servers()

    mcp_servers = {}

    for server in servers:
        server_name = server.get("name", "")
        transport = server.get("transport", "")
        port = server.get("port")

        if not server_name or not transport:
            continue

        if transport == "stdio":
            # For stdio servers, FastMCP runs the actual MCP server command
            command = server.get("command", "")
            arguments = server.get("arguments", [])

            if command:
                # Build the command array as configured in MCPZoo
                cmd_parts = [command]
                if arguments:
                    cmd_parts.extend(arguments)

                mcp_servers[server_name] = {
                    "command": cmd_parts[0],
                    "args": cmd_parts[1:] if len(cmd_parts) > 1 else []
                }

        elif transport in ["http", "sse"] and port:
            # For HTTP/SSE servers, use the standard MCP remote server format
            # FastMCP can connect directly to the running MCP server
            base_url = f"http://localhost:{port}"

            mcp_servers[server_name] = {
                "url": base_url,
                "transport": transport
            }

    return {"mcpServers": mcp_servers}

@router.post("/parse-config")
async def parse_server_config(
    data: dict,
    username: str = Depends(verify_token),
):
    """Parse and validate JSON configuration for MCP server."""
    logger.info(f"parse_server_config called by user: {username}")
    try:
        json_str = data.get("json", "")
        if not json_str:
            logger.warning("No JSON configuration provided")
            raise HTTPException(status_code=400, detail="JSON configuration is required")

        # Parse JSON
        try:
            config_data = json.loads(json_str)
            logger.info(f"Parsed JSON: {config_data}")
        except json.JSONDecodeError as e:
            logger.warning(f"Invalid JSON: {str(e)}")
            raise HTTPException(status_code=400, detail=f"Invalid JSON: {str(e)}")

        # Check if it's McpServersJsonFile format (has mcpServers key)
        if "mcpServers" in config_data and isinstance(config_data["mcpServers"], dict):
            logger.info("Detected McpServersJsonFile format")
            # Convert from McpServersJsonFile format to MCPServerConfig
            mcp_servers = config_data["mcpServers"]
            if len(mcp_servers) != 1:
                logger.warning(f"McpServersJsonFile contains {len(mcp_servers)} servers, expected 1")
                raise HTTPException(
                    status_code=400,
                    detail="McpServersJsonFile must contain exactly one server configuration"
                )

            server_name, server_config = next(iter(mcp_servers.items()))
            logger.info(f"Converting server '{server_name}' with config: {server_config}")

            # Auto-detect transport based on presence of url
            if server_config.get("url"):
                transport = "http"  # Default to HTTP for URLs
                logger.info(f"Auto-detected transport: {transport} (url present: {bool(server_config.get('url'))})")
            else:
                transport = server_config.get("type", "stdio").lower()
                logger.info(f"Using specified transport: {transport}")
            
            # Convert to MCPServerConfig format
            mcpserver_config = {
                "name": server_name,
                "transport": transport,
                "command": server_config.get("command"),
                "arguments": server_config.get("args", []),
                "url": server_config.get("url"),
                "envs": server_config.get("env", {}),
                "headers": server_config.get("headers", {}),
            }
            logger.info(f"Converted config: {mcpserver_config}")

            # Validate using MCPServerConfig model
            server_config_obj = Server.model_validate(mcpserver_config)
            logger.info("Validation successful")
            return server_config_obj.model_dump()

        else:
            logger.info("Assuming direct MCPServerConfig format")
            # Assume it's already MCPServerConfig format
            # Validate using MCPServerConfig model
            server_config = Server.model_validate(config_data)
            logger.info("Validation successful")
            return server_config.model_dump()

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to parse configuration: {str(e)}", exc_info=True)
        raise HTTPException(status_code=400, detail=f"Failed to parse configuration: {str(e)}")

@router.post("/{server_id}/files", response_model=dict)
async def get_server_files(
    server_id: int,
    server_config_data: dict | None = None,
    username: str = Depends(verify_token),
    db_service: DatabaseService = Depends(get_database_service),
):
    """Get generated files for a server configuration."""
    logger.info(f"get_server_files called by user: {username} for server_id: {server_id}")
    try:
        # Use provided server config data if available, otherwise fetch from database
        if server_config_data:
            logger.info(f"Using provided server config data for server: {server_id}")
            server_config = Server.model_validate(server_config_data)
        else:
            logger.info(f"Fetching server config from database for server: {server_id}")
            db = db_service.get_db()
            server_config = db.get_server(server_id)

            if not server_config:
                logger.warning(f"Server not found: {server_id}")
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail="Server not found",
                )

        # Get server directory (server_config is already a Pydantic Server model)
        directory = server_config.get_server_directory()


        # Create file generators
        mcp_servers_json = directory.mcp_servers_json_file
        fastmcp_proxy = directory.fastmcp_server_proxy_server_file
        mise_toml = directory.mise_toml_file
        supervisord_conf = directory.supervisord_program_config

        # Generate file contents
        files = {
            "mcpServers.json": str(mcp_servers_json),
            "server.py": str(fastmcp_proxy),
            "mise.toml": str(mise_toml),
            "supervisord.conf": str(supervisord_conf),
        }

        logger.info(f"Successfully generated files for server: {server_id}")
        return {"files": files}
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        logger.error(f"Error in get_server_files for {server_id}: {str(e)}\n{traceback.format_exc()}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error generating server files: {str(e)}"
        ) from e
